function [fitresult, gof] = createFit(x, y, h)
%CREATEFIT(X,Y,H)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: h
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Aug-2015 15:38:52


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( x, y, h );

% Set up fittype and options.
ft = fittype( 'a*exp(-((x-b).^2)/(2*c^2)-((y-d).^2)/(2*e^2))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [10 0 0.5 0 0.5];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h_1 = plot( fitresult, [xData, yData], zData );
legend( h_1, 'untitled fit 1', 'h vs. x, y', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
zlabel h
grid on
view( -119.5, 12.0 );


