% John Canty                                    % Created 09/08/15
% Yildiz Lab

% Extracts a list of drift-corrected coordinates and intensity values from
% a single-cell epifluorescence Z-stack. Also extracts the coordinates from
% analyzed telomere clusters from a STORM movie. Matches the coordinates
% and generates a correlation plot of spot intensity vs cluster size.

% Function calls:
% GaussFit.m - generates a bivariate Gaussian fit to the cluster

%%---------------Extract Z-stack Ints/Coords ---------------------
% Change working directory to 
clear all;

dirData = dir('*.txt');
num = length(dirData);
data_list = [];

for i = 1:num
    field = dirData(i);
    
    fname = field.name;
    if strfind(fname,'roi')
        info = tdfread(fname,'\t');
        ints = info.I;
        x_c = info.Xc; 
        y_c = info.Yc;
        data = horzcat(ints,x_c,y_c);
        data_list = vertcat(data_list,data);
    else
        continue
    end
end

pause 

%%----------------Extract centroid values --------------------------
% Navigate to folder containing clusters generated by STORM
clear dirData;
clear num;

folder = uigetdir;
cd(folder);
dirData = dir('*.txt');
num = length(dirData);

centroid_list = []
for i = 1:num
    field = dirData(i);
    fname = field.name;
    if strfind(fname,'output')
        info = dlmread(fname,'\t');
        [kmax,ind] = max(info(:,3));
        data = info(ind,:)
        centroid_list = vertcat(centroid_list,data);
    else
        continue
    end
end

%%---------------Match coordinate values----------------------------





%%---------------Generate correlation plot--------------------------